enum TYPES {
  START_GAME = 'START_GAME',
  UPDATE_CONFIG = 'UPDATE_CONFIG',
  GENERATE_EXERICES = 'GENERATE_EXERICES',
  SUBMIT_ANSWER = 'SUBMIT_ANSWER',
  INCREASE_SCORE = 'INCREASE_SCORE',
  UPDATE_DIFFICULTY = "UPDATE_DIFFICULTY"
}

export default TYPES;
